# Generated by Django 4.2.2 on 2023-07-10 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        '^[a-zA-Zа-яА-Я\\s\\-]+$',
                        'Only letters, spaces, and hyphens are allowed.',
                    ),
                ],
                verbose_name='first name',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        '^[a-zA-Zа-яА-Я\\s\\-]+$',
                        'Only letters, spaces, and hyphens are allowed.',
                    ),
                ],
                verbose_name='last name',
            ),
        ),
    ]
