# Generated by Django 4.2.2 on 2023-07-10 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='created_at',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='updated_at',
            ),
        ),
    ]
