# Generated by Django 4.2.2 on 2023-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
