# Generated by Django 4.2.2 on 2023-07-28 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscriber',
            new_name='subscribed',
        ),
    ]
