# Generated by Django 4.2.4 on 2023-08-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_rename_subscriber_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
