# Generated by Django 4.2.2 on 2023-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_rename_subscriber_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
