# Generated by Django 4.2.3 on 2023-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
