# Generated by Django 4.2.3 on 2023-08-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                error_messages={'unique': 'A user with that username already exists!'},
                max_length=50,
                unique=True,
            ),
        ),
    ]
