# Generated by Django 4.2.2 on 2023-07-17 18:57

import uuid

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='created_at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated_at'),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                (
                    'source_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='source name',
                    ),
                ),
                (
                    'source_link',
                    models.URLField(
                        blank=True,
                        max_length=2047,
                        null=True,
                        verbose_name='source link',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(default=False, verbose_name='is published'),
                ),
                (
                    'views_count',
                    models.IntegerField(default=0, editable=False, verbose_name='views'),
                ),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name='Tag name',
                    ),
                ),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                (
                    'parent',
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='children',
                        to='articles.tag',
                        verbose_name='Parent category',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'article',
                    models.ForeignKey(
                        help_text='select article',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='articles.article',
                        verbose_name='article',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='select user',
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'favorite article',
                'verbose_name_plural': 'favorite articles',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=mptt.fields.TreeManyToManyField(
                blank=True,
                related_name='articles',
                to='articles.tag',
                verbose_name='tags',
            ),
        ),
        migrations.AddConstraint(
            model_name='favoritearticle',
            constraint=models.UniqueConstraint(
                fields=('article', 'user'),
                name='articles_favoritearticle_unique_favorite',
            ),
        ),
    ]
