# Generated by Django 4.2.2 on 2023-07-20 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='articles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='article',
            field=models.ForeignKey(
                help_text='select article',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_articles',
                to='articles.article',
                verbose_name='article',
            ),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='user',
            field=models.ForeignKey(
                help_text='select user',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_articles',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
