# Generated by Django 4.2.2 on 2023-07-09 01:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name='Tag name',
                    ),
                ),
                ('slug', models.SlugField(unique=True)),
                (
                    'children',
                    models.ManyToManyField(
                        blank=True,
                        related_name='prnts',
                        to='articles.tag',
                        verbose_name='Children',
                    ),
                ),
                (
                    'parents',
                    models.ManyToManyField(
                        blank=True,
                        related_name='chldrn',
                        to='articles.tag',
                        verbose_name='Parents',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='articles',
                to='articles.tag',
                verbose_name='tags',
            ),
        ),
    ]
