# Generated by Django 4.2.2 on 2023-07-10 20:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_tag_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'article',
                    models.ForeignKey(
                        help_text='select article',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='articles.article',
                        verbose_name='article',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='select user',
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'favorite article',
                'verbose_name_plural': 'favorite articles',
            },
        ),
        migrations.AddConstraint(
            model_name='favoritearticle',
            constraint=models.UniqueConstraint(
                fields=('article', 'user'),
                name='articles_favoritearticle_unique_favorite',
            ),
        ),
    ]
