# Generated by Django 4.2.2 on 2023-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_alter_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='annotation',
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name='annotation',
            ),
        ),
    ]
