# Generated by Django 4.2.2 on 2023-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0003_article_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=models.CharField(
                default='',
                max_length=400,
                verbose_name='annotation',
            ),
            preserve_default=False,
        ),
    ]
