# Generated by Django 4.2.3 on 2023-08-08 22:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views_count',
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'ipaddress',
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        verbose_name='IP address',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(related_name='articles', to='articles.viewer'),
        ),
    ]
