# Generated by Django 4.2.3 on 2023-08-09 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_alter_viewer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='articles',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='viewers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
