[tool.black]
skip-string-normalization=true
skip-magic-trailing-comma=false
line-length=89

[tool.flake8]
ignore=['WPS100', 'W503', 'D100', 'D101', 'D102', 'D103', 'D104', 'D105', 'D106', 'D107']
exclude=['.git', 'env/', 'venv/', 'temp/', '*.md', '__pycache__/']
max-cognitive-complexity=10
max-line-length=89
class_attributes_order=['field', 'meta_class', 'nested_class', 'magic_method', 'property_method', 'static_method', 'class_method', 'method', 'private_method']

[tool.isort]
known_first_party=['users', 'api', 'core', 'likes']
profile='black'

[tool.mypy]
exclude=['venv/']
ignore_missing_imports=true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "stethoscope.settings"
