# Generated by Django 4.2.3 on 2023-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('likes', '0004_alter_vote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={
                'ordering': ['-object_id'],
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
            },
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(
                choices=[(1, 'Like'), (-1, 'Dislike')],
                verbose_name='vote',
            ),
        ),
    ]
