# Generated by Django 4.2.2 on 2023-07-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('articles', '0003_article_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopArticles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'articles',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='articles',
                        to='articles.article',
                        verbose_name='Article',
                    ),
                ),
            ],
        ),
    ]
