# Generated by Django 4.2.3 on 2023-08-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0005_alter_article_author'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopArticle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'article',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='top_article',
                        to='articles.article',
                        verbose_name='TopArticle',
                    ),
                ),
            ],
            options={
                'verbose_name': 'TopArticle',
                'verbose_name_plural': 'TopArticles',
                'ordering': ('-pk',),
            },
        ),
        migrations.DeleteModel(
            name='TopArticles',
        ),
    ]
